name: Tests
'on': [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
          environment-file: environment.yaml
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          auto-activate-base: false
          activate-environment: airflow
    - run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show

