name: Tests
'on': [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: install_mamba
        run: |
          conda config --add channels conda-forge
          conda install mamba -n base -c conda-forge
      
      - name: make_mamba_env
        run: |
          mamba env create -f environment.yaml
